language: objective-c
osx_image: xcode10
script:
  - brew install swiftlint || brew upgrade swiftlint
  - swiftlint lint --config .swiftlint.yml
  - cd Example
  - xcodebuild -version
  - xcodebuild -project PerspectiveExample.xcodeproj -scheme PerspectiveTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF ios
